version: "3.2"
services:
  mongod:
    build: ./mongod
    networks:
      - webnet
    volumes:
      - type: volume
        source: mongo_data
        target: /var/lib/mongodb
    restart: always
    ports:
      - "27017:27017"
  redis:
    build: ./redis
    networks:
      - webnet
    volumes:
      - type: volume
        source: redis_data
        target: /var/lib/redis
    restart: always
    ports:
      - "6379:6379"
  nginx:
    build: ./nginx
    ports:
      - "8080:8080"
    networks:
      - webnet
    # volumes:
    #   - type: volume
    #     source: /Users/lionel/code/dashboard-webapp
    #     target: /etc/nginx/html
    volumes:
    - /Users/lionel/code/dashboard-webapp:/etc/nginx/html
    restart: always
networks:
  webnet:
volumes:
  mongo_data:
  redis_data: